### ISSUE TITLE
Error during module import

### ISSUE THREAD

**Issue by OlegXio** [MathisJANKOVIC/py-console-menu#2]
```
Traceback (most recent call last):
  File "D:\PycharmProjects\python_climenu\main.py", line 1, in <module>
    from pythonclimenu import menu
  File "D:\Program Files\Python310\lib\site-packages\pythonclimenu\__init__.py", line 1, in <module>
    from .climenu import menu
  File "D:\Program Files\Python310\lib\site-packages\pythonclimenu\climenu.py", line 28, in <module>
    _TERMINAL_HEIGHT = os.get_terminal_size().lines
OSError: [WinError 6] Неверный дескриптор
```

**Comment by OlegXio** [comment]
Upd.: the error is observed only when running PyCharm in the terminal (Run tab)

**Comment by mathisjankovic** [comment]
Hello

Thank you for the precision. It looks like you're encountering an issue specific to the PyCharm Console. The library uses the os.get_terminal_size method, and apparently, it doesn't work as expected in this environment. Even when switching methods to get the size of the terminal, the menu still doesn't work correctly.

It appears that the PyCharm console has a unique way of handling terminal operations, which can cause such issues. I tested the library on Windows, macOS, and Linux terminals, where it works as intended. I will need to debug the library specifically for the PyCharm environment.

For now, I suggest using the library in standard terminals. Sorry for the trouble and thank you for understanding.
